import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiTypescript,
  SiBootstrap,
  SiTailwindcss,
  SiZod,
  SiReactquery,
  SiRedux,
  SiReact,
  SiNodedotjs,
  SiPrisma,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiJsonwebtokens,
  SiDocker,
  SiNginx,
  SiNestjs,
  SiFastify,
  SiBun,
  SiGo,
  SiSocketdotio,
  SiPuppeteer,
  SiJson,
  SiAxios,
  SiCheerio,
  SiTimescale,
  SiRelianceindustrieslimited,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  typescript: SiTypescript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  bootstrap: SiBootstrap,
  tailwind: SiTailwindcss,
  zod: SiZod,
  reactquery: SiReactquery,
  redux: SiRedux,
  react: SiReact,
  nodejs: SiNodedotjs,
  prisma: SiPrisma,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  redis: SiRedis,
  jwt: SiJsonwebtokens,
  docker: SiDocker,
  nginx: SiNginx,
  nestjs: SiNestjs,
  fastify: SiFastify,
  bun: SiBun,
  golang: SiGo,
  socket: SiSocketdotio,
  puppeteer: SiPuppeteer,
  json: SiJson,
  axios: SiAxios,
  cheerio: SiCheerio,
  cron: SiTimescale,
  limit: SiRelianceindustrieslimited,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
